# Generated by Django 6.0.4 on 2026-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'utilizadores',
            },
        ),
    ]
