# Generated by Django 6.0.4 on 2026-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_utilizador_bio_utilizador_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='tipo',
        ),
    ]
