# Generated by Django 6.0.4 on 2026-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_utilizador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=10),
        ),
    ]
