# Generated by Django 6.0.4 on 2026-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_mensagem_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(blank=True),
        ),
    ]
