# Generated by Django 6.0.4 on 2026-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_mensagem_audio_alter_mensagem_mensagem'),
        ('usuarios', '0004_add_tipo_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ornamental', 'Ornamental'), ('medicinal', 'Medicinal'), ('fruteira', 'Fruteira'), ('aromatica', 'Aromática')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('cliente', 'vendedor')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('cliente', 'planta')},
        ),
    ]
